# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

trigger:
- master

pr: none

steps:
# Install the latest version of the dotnet sdk
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.302

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: VSTest@2
  displayName: 'VsTest'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\**\*.Tests.dll
     !**\obj\**
    codeCoverageEnabled: false
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publishing App...'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: 5.2.0

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: src/NodaTimePicker/NodaTimePicker.csproj

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)